"""Local-energy-scale heuristic drive schedule generation for QUBO solving."""

from __future__ import annotations

import warnings

import numpy as np
import torch
from numpy.typing import NDArray

import qoolqit
from qubosolver import Instance

from ._device_specs import (
    detuning_amplitude_ratio,
    max_virtual_amplitude,
    pulser_specs as _pulser_specs,
)
from ._waveforms import constant_weighted_dmm


def build_drive(
    instance: Instance,
    register: qoolqit.Register,
    *,
    device: qoolqit.Device,
    dmm: bool = False,
    kappa: float = 0.25,
) -> qoolqit.Drive:
    r"""Generate a local-energy-scale heuristic drive for QUBO solving.

    For each qubit, the local physical energy scale is

        E_i = |delta_i(T)| + sum_{j != i} |V_ij|,

    where delta_i(T) is the final detuning effectively applied to qubit i
    and V_ij is the physical interaction generated by the embedded register.

    The peak Rabi frequency is defined as

        omega_max = kappa * mean_i(E_i).

    When DMM is available, the final local detunings are encoded as

        delta_i(T) = delta_g(T) + delta_dmm(T) * w_i,

    with

        delta_g(T)   = d_max,
        delta_dmm(T) = -(d_max - d_min),
        w_i          = (d_max - d_i) / (d_max - d_min).

    Without DMM, all atoms receive the same final global detuning

        delta_i(T) = delta_g(T) = mean_i(d_i).

    The resulting amplitude and detuning waveforms are clamped or rescaled
    when necessary so they remain compilable on the target device.

    Args:
        instance: The QUBO instance whose diagonal encodes target detunings.
        register: The physical register the drive will run on.
        device: Target quantum device providing the hardware limits.
        dmm: Whether to use the Detuning Map Modulator for local control.
        kappa: Ratio between the peak Rabi frequency and the average local
            physical energy scale.

    Returns:
        A drive ready for compilation and execution.
    """
    # Hardware bounds
    specs = device.specs
    max_seq_duration: float = (
        specs["max_duration"]
        or 1000.0
    )

    pulser_specs = _pulser_specs(device)

    use_dmm = (
        dmm
        and pulser_specs["dmm_bottom_detuning"]
        is not None
    )

    if (
        specs.get("max_amplitude") is not None
        and specs.get("max_abs_detuning") is not None
    ):
        device_max_amplitude = specs["max_amplitude"]
        device_max_abs_detuning = specs[
            "max_abs_detuning"
        ]

        assert device_max_amplitude is not None
        assert device_max_abs_detuning is not None

        det_amp_ratio = (
            device_max_amplitude
            / device_max_abs_detuning
        )

        if kappa < det_amp_ratio:
            warnings.warn(
                f"local_energy_scale_kappa is too small "
                f"({kappa}), you're likely to get a "
                "qoolqit CompilationError. "
                f"Set it above {det_amp_ratio}."
            )

    n = instance.size

    # Target local final detunings.
    d: NDArray[np.float64] = np.asarray(
        (
            -0.5
            * torch.diag(instance.matrix)
        )
        .detach()
        .cpu()
        .numpy(),
        dtype=np.float64,
    )

    d_min = float(np.min(d))
    d_max = float(np.max(d))

    weights: list[float]

    if use_dmm:
        # The final global detuning is the highest
        # target value. The DMM locally pulls the
        # detuning down.
        delta_g_T = d_max

        spread = max(
            0.0,
            d_max - d_min,
        )

        if spread > 1e-15:
            # WeightedDetuning waveforms must be
            # non-positive.
            delta_dmm_T = -spread

            normalized_weights = np.divide(
                np.subtract(
                    np.float64(d_max),
                    d,
                ),
                np.float64(spread),
            )

            weights = np.clip(
                normalized_weights,
                0.0,
                1.0,
            ).tolist()
        else:
            use_dmm = False
            delta_g_T = float(np.mean(d))
            delta_dmm_T = 0.0
            weights = [0.0] * n
    else:
        # Without DMM, all atoms receive the same
        # final global detuning.
        delta_g_T = float(np.mean(d))
        delta_dmm_T = 0.0
        weights = [0.0] * n

    # Final detuning effectively applied to each
    # qubit:
    #
    # delta_i(T) =
    #     delta_g(T) + delta_dmm(T) * w_i.
    if use_dmm:
        weights_array: NDArray[np.float64] = (
            np.asarray(
                weights,
                dtype=np.float64,
            )
        )

        final_local_detunings: NDArray[
            np.float64
        ] = np.add(
            np.float64(delta_g_T),
            np.multiply(
                np.float64(delta_dmm_T),
                weights_array,
            ),
        )
    else:
        final_local_detunings = np.full(
            n,
            delta_g_T,
            dtype=np.float64,
        )

    # Physical interactions generated by the
    # embedded register:
    #
    # V_ij = 1 / r_ij**6.
    physical_interactions = (
        register.interactions()
    )

    # Associate each register qubit ID with its
    # position in the local-energy vector.
    qubit_index = {
        qubit_id: index
        for index, qubit_id in enumerate(
            register.qubits_ids
        )
    }

    # For each qubit i, compute:
    #
    # sum_{j != i} |V_ij|.
    interaction_scale: NDArray[np.float64] = (
        np.zeros(
            n,
            dtype=np.float64,
        )
    )

    for (
        qubit_i,
        qubit_j,
    ), interaction in physical_interactions.items():
        index_i = qubit_index[qubit_i]
        index_j = qubit_index[qubit_j]

        interaction_magnitude = abs(
            float(interaction)
        )

        interaction_scale[index_i] += (
            interaction_magnitude
        )

        interaction_scale[index_j] += (
            interaction_magnitude
        )

    # Local physical energy scale:
    #
    # E_i = |delta_i(T)|
    #       + sum_{j != i} |V_ij|.
    local_energy_scale: NDArray[np.float64] = (
        np.add(
            np.abs(final_local_detunings),
            interaction_scale,
        )
    )

    # Average local physical energy scale:
    #
    # E_mean = (1 / n) * sum_i E_i.
    mean_local_energy_scale = float(
        np.mean(local_energy_scale)
    )

    # Local-energy-scale mixing rule:
    #
    # omega_max = kappa * E_mean.
    omega_max = float(
        kappa * mean_local_energy_scale
    )

    # Clamp the amplitude to what can be compiled
    # for this device and register.
    max_amplitude = float(
        max_virtual_amplitude(
            device,
            register,
        )
    )

    if omega_max > max_amplitude:
        warnings.warn(
            "The local-energy-scale drive amplitude "
            f"({omega_max}) exceeds the maximum "
            "amplitude compilable on the device for "
            f"this register ({max_amplitude}); "
            "clamping to it."
        )

        omega_max = max_amplitude

    # Ensure that the target detunings remain
    # compilable for the selected amplitude.
    max_detuning = float(
        detuning_amplitude_ratio(device)
        * omega_max
        * (1.0 - 1e-3)
    )

    max_abs_d = float(
        np.max(np.abs(d))
    )

    if max_abs_d > max_detuning:
        warnings.warn(
            "The local-energy-scale detuning "
            f"({max_abs_d}) exceeds the maximum "
            "detuning compilable on the device for "
            f"this amplitude ({max_detuning}); "
            "scaling the detuning down."
        )

        d = np.multiply(
            d,
            np.float64(
                max_detuning / max_abs_d
            ),
        )

        d_min = float(np.min(d))
        d_max = float(np.max(d))

        # Recompute the DMM encoding after
        # rescaling the target local detunings.
        if use_dmm:
            delta_g_T = d_max

            spread = max(
                0.0,
                d_max - d_min,
            )

            if spread > 1e-15:
                delta_dmm_T = -spread

                normalized_weights = np.divide(
                    np.subtract(
                        np.float64(d_max),
                        d,
                    ),
                    np.float64(spread),
                )

                weights = np.clip(
                    normalized_weights,
                    0.0,
                    1.0,
                ).tolist()
            else:
                use_dmm = False
                delta_dmm_T = 0.0
                weights = [0.0] * n
                delta_g_T = float(
                    np.mean(d)
                )
        else:
            delta_g_T = float(np.mean(d))
            delta_dmm_T = 0.0
            weights = [0.0] * n

    # Keep the initial detuning rule identical to
    # the standard heuristic drive.
    delta_0 = -float(
        np.max(np.abs(d))
    )

    # Amplitude waveform:
    # 0 -> omega_max -> omega_max -> 0.
    eps = 1e-9

    amp_wave = qoolqit.InterpolatedWaveform(
        max_seq_duration,
        [
            eps,
            omega_max,
            omega_max,
            eps,
        ],
    )

    # Global detuning waveform:
    # initial negative value -> final target.
    det_wave = qoolqit.InterpolatedWaveform(
        max_seq_duration,
        [
            delta_0,
            delta_0,
            delta_g_T,
            delta_g_T,
        ],
    )

    # Optional DMM weighted detunings.
    wdetunings = None

    if use_dmm:
        energy_scale = float(
            device._target_amp
            / omega_max
        )

        wdetunings = constant_weighted_dmm(
            weights,
            max_seq_duration,
            final_detuning=delta_dmm_T,
            device=device,
            energy_scale=energy_scale,
        )

    return qoolqit.Drive(
        amplitude=amp_wave,
        detuning=det_wave,
        dmm=wdetunings,
    )