"""Local-energy-scale heuristic drive schedule generation for QUBO solving."""

from __future__ import annotations

import logging

import torch

import qoolqit
from qubosolver import Instance, matrix, Vector

from ._device_specs import (
    detuning_amplitude_ratio,
    max_virtual_amplitude,
    pulser_specs as _pulser_specs,
)
from ._waveforms import constant_weighted_dmm

logger = logging.getLogger(__name__)


def _detunings(d: Vector, use_dmm: bool) -> tuple[float, float, Vector, bool]:

    d_min = d.min().item()
    d_max = d.max().item()

    if use_dmm:
        # The final global detuning is the highest
        # target value. The DMM locally pulls the
        # detuning down.
        delta_g_T = d_max

        spread = max(0.0, d_max - d_min)

        if spread > 1e-15:
            # WeightedDetuning waveforms must be
            # non-positive.
            delta_dmm_T = -spread
            denom = d_max - d_min
            weights = ((d_max - d) / denom).clip(0.0, 1.0)
        else:
            use_dmm = False
            delta_g_T = d.mean().item()
            delta_dmm_T = 0.0
            weights = torch.zeros_like(d)
    else:
        # Without DMM, all atoms receive the same
        # final global detuning.
        delta_g_T = d.mean().item()
        delta_dmm_T = 0.0
        weights = torch.zeros_like(d)

    return delta_g_T, delta_dmm_T, weights, use_dmm


def build_drive(
    instance: Instance,
    register: qoolqit.Register,
    *,
    device: qoolqit.Device,
    dmm: bool = False,
    kappa: float = 0.25,
) -> qoolqit.Drive:
    r"""Generate a local-energy-scale heuristic drive for QUBO solving.

    For each qubit, the local physical energy scale is

    $$E_i = |\delta_i(T)| + \sum_{j \neq i} |V_{ij}|,$$

    where $\delta_i(T)$ is the final detuning effectively applied to qubit
    $i$ and $V_{ij}$ is the physical interaction generated by the embedded
    register.

    The peak Rabi frequency is defined as

    $$\omega_{\max} = \kappa \cdot \text{mean}_i(E_i).$$

    When DMM is available, the final local detunings are encoded as

    $$\delta_i(T) = \delta_g(T) + \delta_{\text{dmm}}(T) \cdot w_i,$$

    with

    $$\delta_g(T) = d_{\max}, \quad
    \delta_{\text{dmm}}(T) = -(d_{\max} - d_{\min}), \quad
    w_i = \frac{d_{\max} - d_i}{d_{\max} - d_{\min}}.$$

    Without DMM, all atoms receive the same final global detuning

    $$\delta_i(T) = \delta_g(T) = \text{mean}_i(d_i).$$

    The resulting amplitude and detuning waveforms are clamped or rescaled
    when necessary so they remain compilable on the target device.

    Args:
        instance: The QUBO instance whose diagonal encodes target detunings.
        register: The physical register the drive will run on.
        device: Target quantum device providing the hardware limits.
        dmm: Whether to use the Detuning Map Modulator for local control.
        kappa: Ratio between the peak Rabi frequency and the average local
            physical energy scale.

    Returns:
        A drive ready for compilation and execution.
    """
    # Hardware bounds
    specs = device.specs
    max_seq_duration: float = specs["max_duration"] or 1000.0
    pulser_specs = _pulser_specs(device)
    use_dmm = dmm and (pulser_specs["dmm_bottom_detuning"] is not None)

    if specs.get("max_amplitude") is not None and specs.get("max_abs_detuning") is not None:
        device_max_amplitude = specs["max_amplitude"]
        device_max_abs_detuning = specs["max_abs_detuning"]
        assert device_max_amplitude is not None
        assert device_max_abs_detuning is not None

        det_amp_ratio = device_max_amplitude / device_max_abs_detuning

        if kappa < det_amp_ratio:
            logger.warning(
                f"local_energy_scale_kappa is too small ({kappa}), you're likely to get a qoolqit CompilationError. Set it above {det_amp_ratio}."
            )

    # Target local final detunings.
    d = (-0.5 * torch.diag(instance.matrix)).detach().cpu()
    delta_g_T, delta_dmm_T, weights, use_dmm = _detunings(d, use_dmm)

    # Final detuning effectively applied to each qubit:
    #
    # delta_i(T) = delta_g(T) + delta_dmm(T) * w_i.
    #
    # with delta_dmm(T) = 0 when dmm is disabled
    final_local_detunings = delta_g_T + delta_dmm_T * weights

    # Physical interactions generated by the embedded register:
    #
    # V_ij = 1 / r_ij**6.
    #
    # For each qubit i, compute:
    #
    # sum_{j != i} |V_ij|.
    interaction_scale = matrix.tensor(register.interaction_matrix()).abs().sum(dim=0)

    # Local physical energy scale:
    #
    # E_i = |delta_i(T)| + sum_{j != i} |V_ij|.
    local_energy_scale = final_local_detunings.abs() + interaction_scale

    # Average local physical energy scale:
    #
    # E_mean = (1 / n) * sum_i E_i.
    mean_local_energy_scale = local_energy_scale.mean().item()

    # Local-energy-scale mixing rule:
    #
    # omega_max = kappa * E_mean.
    omega_max = kappa * mean_local_energy_scale

    # Clamp the amplitude to what can be compiled for this device and register.
    max_amplitude = max_virtual_amplitude(device, register)

    if omega_max > max_amplitude:
        logger.info(
            f"The local-energy-scale drive amplitude ({omega_max}) exceeds the maximum "
            f"amplitude compilable on the device for this register "
            f"({max_amplitude}); clamping to it."
        )
        omega_max = max_amplitude

    # Ensure that the target detunings remain compilable for the selected amplitude.
    max_detuning = detuning_amplitude_ratio(device) * omega_max * (1.0 - 1e-3)
    max_abs_d = d.abs().max().item()

    if max_abs_d > max_detuning:
        logger.info(
            f"The local-energy-scale detuning ({max_abs_d}) exceeds the maximum detuning "
            f"compilable on the device for this amplitude ({max_detuning}); "
            f"scaling the detuning down."
        )
        d = d * (max_detuning / max_abs_d)
        # Recompute the DMM encoding after rescaling the target local detunings.
        delta_g_T, delta_dmm_T, weights, use_dmm = _detunings(d, use_dmm)

    # Keep the initial detuning rule identical to the standard heuristic drive.
    delta_0 = -d.abs().max().item()

    # Amplitude waveform: 0 -> omega_max -> omega_max -> 0.
    eps = 1e-9
    amp_wave = qoolqit.InterpolatedWaveform(
        max_seq_duration,
        [eps, omega_max, omega_max, eps],
    )

    # Global detuning waveform: initial negative value -> final target.
    det_wave = qoolqit.InterpolatedWaveform(
        max_seq_duration,
        [delta_0, delta_0, delta_g_T, delta_g_T],
    )

    # Optional DMM weighted detunings.
    wdetunings = None

    if use_dmm:
        energy_scale = device._target_amp / omega_max
        wdetunings = constant_weighted_dmm(
            weights.tolist(),
            max_seq_duration,
            final_detuning=delta_dmm_T,
            device=device,
            energy_scale=energy_scale,
        )

    return qoolqit.Drive(
        amplitude=amp_wave,
        detuning=det_wave,
        dmm=wdetunings,
    )
