name: Publish

on:
    release:
        types:
            [published]

permissions:
    contents: read

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    publish_pypi:
        name: Publish package to PyPI
        runs-on: ubuntu-latest
        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write
        steps:
        - name: Checkout
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            ref: ${{ github.ref }}
        - name: Install uv
          uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
          with:
            version: 0.11.30
            python-version: "3.14"
        - name: Build and publish package
          run: |
            uv build
        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        - name: Confirm deployment
          timeout-minutes: 5
          run: |
            VERSION=${GITHUB_REF#refs/tags/v}
            until pip download qubo-solver==$VERSION
            do
                echo "Failed to download from PyPI, will wait for upload and retry."
                sleep 1
            done

    public_docs:
        name: Publish docs to github pages
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Install uv
          uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
          with:
            version: 0.11.30
            python-version: '3.14'
        - name: Deploy docs
          run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git fetch origin gh-pages
            uv run --group doc --no-default-groups mike deploy --push --update-aliases ${{ github.ref_name }} latest
        permissions:
            contents: write # TODO: wide permissions needed for deployment with mike

    betterleaks-gh-pages:
        name: Secret Detection (gh-pages)
        needs: [public_docs]
        permissions:
            contents: read
            security-events: write
        uses: pasqal-io/qubo-solver/.github/workflows/betterleaks.yml@main
        with:
            scan_gh_pages: true
